// Δεδομένα του παιχνιδιού: γράμματα, λέξεις με εικόνες (emoji), λέξεις για τα lego.

const LETTERS = [
  { l: 'α', u: 'Α', name: 'άλφα', v: true },
  { l: 'β', u: 'Β', name: 'βήτα' },
  { l: 'γ', u: 'Γ', name: 'γάμμα' },
  { l: 'δ', u: 'Δ', name: 'δέλτα' },
  { l: 'ε', u: 'Ε', name: 'έψιλον', v: true },
  { l: 'ζ', u: 'Ζ', name: 'ζήτα' },
  { l: 'η', u: 'Η', name: 'ήτα', v: true },
  { l: 'θ', u: 'Θ', name: 'θήτα' },
  { l: 'ι', u: 'Ι', name: 'γιώτα', v: true },
  { l: 'κ', u: 'Κ', name: 'κάπα' },
  { l: 'λ', u: 'Λ', name: 'λάμδα' },
  { l: 'μ', u: 'Μ', name: 'μι' },
  { l: 'ν', u: 'Ν', name: 'νι' },
  { l: 'ξ', u: 'Ξ', name: 'ξι' },
  { l: 'ο', u: 'Ο', name: 'όμικρον', v: true },
  { l: 'π', u: 'Π', name: 'πι' },
  { l: 'ρ', u: 'Ρ', name: 'ρο' },
  { l: 'σ', u: 'Σ', name: 'σίγμα' },
  { l: 'τ', u: 'Τ', name: 'ταυ' },
  { l: 'υ', u: 'Υ', name: 'ύψιλον', v: true },
  { l: 'φ', u: 'Φ', name: 'φι' },
  { l: 'χ', u: 'Χ', name: 'χι' },
  { l: 'ψ', u: 'Ψ', name: 'ψι' },
  { l: 'ω', u: 'Ω', name: 'ωμέγα', v: true },
];

// Γράμματα που μοιάζουν οπτικά (για πιο ενδιαφέροντα "μπερδευτικά").
const SIM = [
  ['β', 'θ', 'δ', 'ρ', 'φ', 'ψ'],
  ['γ', 'χ', 'ν', 'υ', 'κ'],
  ['ε', 'ξ', 'ζ', 'σ', 'ς'],
  ['μ', 'π', 'τ', 'η', 'λ'],
  ['ο', 'ω', 'σ', 'α', 'φ'],
];

// Γράμματα με ίδιο ήχο στην αρχή λέξης.
const SAME_SOUND = [['η', 'ι', 'υ'], ['ο', 'ω']];

// Συνδυασμοί που δεν σπάμε στο στάδιο 4 (π.χ. "ου", "μπ").
const DIGRAPHS = ['αι', 'ει', 'οι', 'υι', 'ου', 'αυ', 'ευ', 'μπ', 'ντ', 'γκ', 'γγ', 'τσ', 'τζ'];

// Λέξεις με εικόνα: [λέξη, emoji (προσωρινό), αρχείο εικόνας]
// Για κάθε γράμμα με φάκελο εικόνων (π.χ. Α/, Β/, Γ/, Δ/, Ε/, Ζ/, Η/, Θ/, Ι/, Κ/, Ν/, Ξ/, Ο/, Υ/, Φ/, Χ/, Ψ/, Ω/) το emoji δεν χρησιμοποιείται.
const WORDS = [
  ['σελήνη', '', 'img/feggari.webp'],
  ['αγόρι', '', 'img/agori.webp'],
  ['αγελάδα', '', 'img/agelada.webp'],
  ['αεροπλάνο', '', 'img/aeroplano.webp'],
  ['αερόστατο', '', 'img/aerostato.webp'],
  ['αθλητής', '', 'img/athlitis.webp'],
  ['αλεξίπτωτο', '', 'img/alexiptoto.webp'],
  ['αλεπού', '', 'img/alepou.webp'],
  ['άλογο', '', 'img/alogo.webp'],
  ['αρκούδα', '', 'img/arkouda.webp'],
  ['άρρωστος', '', 'img/arrostos.webp'],
  ['αστακός', '', 'img/astakos.webp'],
  ['αστερίας', '', 'img/asterias.webp'],
  ['αστέρι', '', 'img/asteri.webp'],
  ['βέλος', '', 'img/velos.webp'],
  ['βίδα', '', 'img/vida.webp'],
  ['βάζο', '', 'img/vazo.webp'],
  ['βαλίτσα', '', 'img/valitsa.webp'],
  ['βαπόρι', '', 'img/vapori.webp'],
  ['βαρέλι', '', 'img/vareli.webp'],
  ['βάρκα', '', 'img/varka.webp'],
  ['βάτραχος', '', 'img/vatrachos.webp'],
  ['βελόνι', '', 'img/veloni.webp'],
  ['βιβλίο', '', 'img/vivlio.webp'],
  ['βιβλιοθήκη', '', 'img/vivliothiki.webp'],
  ['βιολί', '', 'img/violi.webp'],
  ['βουνό', '', 'img/vouno.webp'],
  ['βούτυρο', '', 'img/voutyro.webp'],
  ['βροχή', '', 'img/vrochi.webp'],
  ['βόδι', '', 'img/vodi.webp'],
  ['γάλα', '', 'img/gala.webp'],
  ['γάμος', '', 'img/gamos.webp'],
  ['γάντια', '', 'img/gadia.webp'],
  ['γαρίδα', '', 'img/garida.webp'],
  ['γάτα', '', 'img/gata.webp'],
  ['γεράκι', '', 'img/geraki.webp'],
  ['γέφυρα', '', 'img/gefyra.webp'],
  ['γη', '', 'img/gi.webp'],
  ['γήπεδο', '', 'img/gipedo.webp'],
  ['γιαγιά', '', 'img/giagia.webp'],
  ['γίγαντας', '', 'img/gigadas.webp'],
  ['γίδα', '', 'img/gida.webp'],
  ['γλώσσα', '', 'img/glossa.webp'],
  ['γόνατο', '', 'img/gonato.webp'],
  ['γορίλας', '', 'img/gorilas.webp'],
  ['γραβάτα', '', 'img/gravata.webp'],
  ['γυαλιά', '', 'img/gyalia.webp'],
  ['δαχτυλίδι', '', 'img/daktylidi.webp'],
  ['δάχτυλο', '', 'img/dachtylo.webp'],
  ['δάσος', '', 'img/dasos.webp'],
  ['δέκα', '', 'img/deka.webp'],
  ['δελφίνι', '', 'img/delfini.webp'],
  ['δέμα', '', 'img/dema.webp'],
  ['δέντρο', '', 'img/dedro.webp'],
  ['δίχτυ', '', 'img/dichty.webp'],
  ['δράκος', '', 'img/drakos.webp'],
  ['δωμάτιο', '', 'img/domatio.webp'],
  ['δώρο', '', 'img/doro.webp'],
  ['δυνατό', '', 'img/dynato.webp'],
  ['έξι', '', 'img/exi.webp'],
  ['εκκλησία', '', 'img/ekklisia.webp'],
  ['ελάφι', '', 'img/elafi.webp'],
  ['ελέφαντας', '', 'img/elefadas.webp'],
  ['ελιά', '', 'img/elia.webp'],
  ['ελικόπτερο', '', 'img/elikoptero.webp'],
  ['εννιά', '', 'img/ennia.webp'],
  ['εστιατόριο', '', 'img/estiatorio.webp'],
  ['εφημερίδα', '', 'img/efimerida.webp'],
  ['εφτά', '', 'img/efta.webp'],
  ['ζάλη', '', 'img/zali.webp'],
  ['ζάρια', '', 'img/zaria.webp'],
  ['ζακέτα', '', 'img/zaketa.webp'],
  ['ζαμπόν', '', 'img/zabon.webp'],
  ['ζάχαρη', '', 'img/zachari.webp'],
  ['ζέβρα', '', 'img/zevra.webp'],
  ['ζελέ', '', 'img/zele.webp'],
  ['ζυγαριά', '', 'img/zygaria.webp'],
  ['ζυμάρι', '', 'img/zymari.webp'],
  ['ζωγραφιά', '', 'img/zografia.webp'],
  ['ζώνη', '', 'img/zoni.webp'],
  ['ηλεκτρισμός', '', 'img/ilektrismos.webp'],
  ['ήλιος', '', 'img/ilios.webp'],
  ['ηλιοτρόπιο', '', 'img/iliotropio.webp'],
  ['ημερολόγιο', '', 'img/imerologio.webp'],
  ['ηφαίστειο', '', 'img/ifaisteio.webp'],
  ['ηχείο', '', 'img/icheio.webp'],
  ['θάλασσα', '', 'img/thalassa.webp'],
  ['θέατρο', '', 'img/theatro.webp'],
  ['θερμόμετρο', '', 'img/thermometro.webp'],
  ['θέση', '', 'img/thesi.webp'],
  ['θησαυρός', '', 'img/thisayros.webp'],
  ['θύελλα', '', 'img/thyella.webp'],
  ['θυμάρι', '', 'img/thymari.webp'],
  ['θυμός', '', 'img/thymos.webp'],
  ['ιγκουάνα', '', 'img/igkouana.webp'],
  ['ινδιάνος', '', 'img/indianos.webp'],
  ['ιπποπόταμος', '', 'img/ippopotamos.webp'],
  ['ιππότης', '', 'img/ippotis.webp'],
  ['ιστιοφόρο', '', 'img/istioforo.webp'],
  ['ιστός', '', 'img/istos.webp'],
  ['κάδος', '', 'img/kados.webp'],
  ['καζάνι', '', 'img/kazani.webp'],
  ['καθρέφτης', '', 'img/kathreftis.webp'],
  ['καμήλα', '', 'img/kamila.webp'],
  ['καμηλοπάρδαλη', '', 'img/kamilopardali.webp'],
  ['καναρίνι', '', 'img/kanarini.webp'],
  ['κανό', '', 'img/kano.webp'],
  ['καπέλο', '', 'img/kapelo.webp'],
  ['καράβι', '', 'img/karavi.webp'],
  ['καρέκλα', '', 'img/karekla.webp'],
  ['κάστρο', '', 'img/kastro.webp'],
  ['κάψουλα', '', 'img/kapsoula.webp'],
  ['κεράσια', '', 'img/kerasia.webp'],
  ['κερί', '', 'img/keri.webp'],
  ['κήπος', '', 'img/kipos.webp'],
  ['κλειδί', '', 'img/kleidi.webp'],
  ['κόκορας', '', 'img/kokoras.webp'],
  ['κοπέλα', '', 'img/kopela.webp'],
  ['κότα', '', 'img/kota.webp'],
  ['κουβάς', '', 'img/kouvas.webp'],
  ['κουνέλι', '', 'img/kouneli.webp'],
  ['κουτί', '', 'img/kouti.webp'],
  ['κρεβάτι', '', 'img/krevati.webp'],
  ['ωδείο', '', 'img/odeio.webp'],
  ['ωκεανός', '', 'img/okeanos.webp'],
  ['ώρα', '', 'img/ora.webp'],
  ['ψαλίδι', '', 'img/psalidi.webp'],
  ['ψαράς', '', 'img/psaras.webp'],
  ['ψάρι', '', 'img/psari.webp'],
  ['ψητό', '', 'img/psito.webp'],
  ['ψυγείο', '', 'img/psygeio.webp'],
  ['ψωμί', '', 'img/psomi.webp'],
  ['φάκελος', '', 'img/fakelos.webp'],
  ['φακός', '', 'img/fakos.webp'],
  ['φάλαινα', '', 'img/falaina.webp'],
  ['φανάρι', '', 'img/fanari.webp'],
  ['φασόλι', '', 'img/fasoli.webp'],
  ['φεγγάρι', '', 'img/feggari.webp'],
  ['φέτα', '', 'img/feta.webp'],
  ['φίδι', '', 'img/fidi.webp'],
  ['φλιτζάνι', '', 'img/flitzani.webp'],
  ['φράουλα', '', 'img/fraoula.webp'],
  ['φτερό', '', 'img/ftero.webp'],
  ['φωτιά', '', 'img/fotia.webp'],
  ['χαλάζι', '', 'img/chalazi.webp'],
  ['χαμόγελο', '', 'img/chamogelo.webp'],
  ['χάρακας', '', 'img/charakas.webp'],
  ['χάρτης', '', 'img/chartis.webp'],
  ['χελώνα', '', 'img/chelona.webp'],
  ['χέρι', '', 'img/cheri.webp'],
  ['χήνα', '', 'img/china.webp'],
  ['χιόνι', '', 'img/chioni.webp'],
  ['χορός', '', 'img/choros.webp'],
  ['χταπόδι', '', 'img/chtapodi.webp'],
  ['χώμα', '', 'img/choma.webp'],
  ['υδρόγειος', '', 'img/ydrogeios.webp'],
  ['ύπνος', '', 'img/ypnos.webp'],
  ['υπολογιστής', '', 'img/ypologistis.webp'],
  ['υφάσματα', '', 'img/yfasmata.webp'],
  ['ύψος', '', 'img/ypsos.webp'],
  ['ύαινα', '', 'img/yaina.webp'],
  ['οδηγός', '', 'img/odigos.webp'],
  ['οδοντόβουρτσα', '', 'img/ododovourtsa.webp'],
  ['οδοντόκρεμα', '', 'img/ododokrema.webp'],
  ['οδοστρωτήρας', '', 'img/odostrotiras.webp'],
  ['οδός', '', 'img/odos.webp'],
  ['οκτώ', '', 'img/okto.webp'],
  ['ομελέτα', '', 'img/omeleta.webp'],
  ['ομπρέλα', '', 'img/obrela.webp'],
  ['όνειρο', '', 'img/oneiro.webp'],
  ['ορχήστρα', '', 'img/orchistra.webp'],
  ['ξαπλώστρα', '', 'img/xaplostra.webp'],
  ['ξενοδοχείο', '', 'img/xenodocheio.webp'],
  ['ξιφίας', '', 'img/xifias.webp'],
  ['ξίφος', '', 'img/xifos.webp'],
  ['ξυλουργός', '', 'img/xylourgos.webp'],
  ['ξυπνητήρι', '', 'img/xypnitiri.webp'],
  ['ξυράφι', '', 'img/xyrafi.webp'],
  ['ξύστρα', '', 'img/xystra.webp'],
  ['ξωτικό', '', 'img/xotiko.webp'],
  ['ξύλα', '', 'img/xyla.webp'],
  ['νήμα', '', 'img/nima.webp'],
  ['νάνος', '', 'img/nanos.webp'],
  ['νεράιδα', '', 'img/neraida.webp'],
  ['νερό', '', 'img/nero.webp'],
  ['νησί', '', 'img/nisi.webp'],
  ['νιπτήρας', '', 'img/niptiras.webp'],
  ['νιφάδα', '', 'img/nifada.webp'],
  ['νόμισμα', '', 'img/nomisma.webp'],
  ['νότα', '', 'img/nota.webp'],
  ['νύφη', '', 'img/nyfi.webp'],
  ['νύχια', '', 'img/nychia.webp'],
  ['νυχτερίδα', '', 'img/nychterida.webp'],
  ['λάδι', '', 'img/ladi.webp'],
  ['λαγός', '', 'img/lagos.webp'],
  ['λάμπα', '', 'img/laba.webp'],
  ['λάχανο', '', 'img/lachano.webp'],
  ['λεμόνι', '', 'img/lemoni.webp'],
  ['λεωφορείο', '', 'img/leoforeio.webp'],
  ['λιβάδι', '', 'img/livadi.webp'],
  ['λιμάνι', '', 'img/limani.webp'],
  ['λιοντάρι', '', 'img/liodari.webp'],
  ['λουκέτο', '', 'img/louketo.webp'],
  ['λουλουδάκι', '', 'img/louloudaki.webp'],
  ['λουλούδι', '', 'img/louloudi.webp'],
  ['λόφος', '', 'img/lofos.webp'],
  ['λύκος', '', 'img/lykos.webp'],
  ['μήλο', '', 'img/milo.webp'],
  ['μαγαζί', '', 'img/magazi.webp'],
  ['μάγος', '', 'img/magos.webp'],
  ['μαθητής', '', 'img/mathitis.webp'],
  ['μαϊμού', '', 'img/maimou.webp'],
  ['μανιτάρι', '', 'img/manitari.webp'],
  ['μαξιλάρι', '', 'img/maxilari.webp'],
  ['μάτι', '', 'img/mati.webp'],
  ['μελάνι', '', 'img/melani.webp'],
  ['μέλι', '', 'img/meli.webp'],
  ['μέλισσα', '', 'img/melissa.webp'],
  ['μέρα', '', 'img/mera.webp'],
  ['μητέρα', '', 'img/mitera.webp'],
  ['μηχανή', '', 'img/michani.webp'],
  ['μολύβι', '', 'img/molyvi.webp'],
  ['μουσική', '', 'img/mousiki.webp'],
  ['μωρό', '', 'img/moro.webp'],
  ['μύτη', '', 'img/myti.webp'],
  ['πάγος', '', 'img/pagos.webp'],
  ['πάπια', '', 'img/papia.webp'],
  ['πίτα', '', 'img/pita.webp'],
  ['παγωτό', '', 'img/pagoto.webp'],
  ['παζάρι', '', 'img/pazari.webp'],
  ['παζλ', '', 'img/pazl.webp'],
  ['πάνα', '', 'img/pani.webp'],
  ['παπαγάλος', '', 'img/papagalos.webp'],
  ['παπί', '', 'img/papi.webp'],
  ['παπούτσι', '', 'img/papoutsi.webp'],
  ['παράθυρο', '', 'img/parathyro.webp'],
  ['πασχαλίτσα', '', 'img/paschalitsa.webp'],
  ['πατάτα', '', 'img/patata.webp'],
  ['πατίνι', '', 'img/patini.webp'],
  ['πεπόνι', '', 'img/peponi.webp'],
  ['πεταλούδα', '', 'img/petalouda.webp'],
  ['πιάνο', '', 'img/piano.webp'],
  ['πιάτο', '', 'img/piato.webp'],
  ['πιγκουίνος', '', 'img/pigkouinos.webp'],
  ['πίτσα', '', 'img/pitsa.webp'],
  ['πλοίο', '', 'img/ploio.webp'],
  ['ποδήλατο', '', 'img/podilato.webp'],
  ['ποντίκι', '', 'img/podiki.webp'],
  ['πόρτα', '', 'img/porta.webp'],
  ['πορτοκάλι', '', 'img/portokali.webp'],
  ['πορτοκαλάδα', '', 'img/portokalada.webp'],
  ['ποτάμι', '', 'img/potami.webp'],
  ['ποτήρι', '', 'img/potiri.webp'],
  ['ποτό', '', 'img/poto.webp'],
  ['πουλί', '', 'img/pouli.webp'],
  ['πρόβατο', '', 'img/provato.webp'],
  ['πόδι', '', 'img/podi.webp'],
  ['σαλάτα', '', 'img/salata.webp'],
  ['σαλιγκάρι', '', 'img/saligkari.webp'],
  ['σαλόνι', '', 'img/saloni.webp'],
  ['σαμπουάν', '', 'img/sabouan.webp'],
  ['σανδάλι', '', 'img/sandali.webp'],
  ['σαξόφωνο', '', 'img/saxofono.webp'],
  ['σαπούνι', '', 'img/sapouni.webp'],
  ['σελίδα', '', 'img/selida.webp'],
  ['σεντόνι', '', 'img/sedoni.webp'],
  ['σημαία', '', 'img/simaia.webp'],
  ['σκάλα', '', 'img/skala.webp'],
  ['σκαντζόχοιρος', '', 'img/skadzochoiros.webp'],
  ['σκύλος', '', 'img/skylos.webp'],
  ['σοκολάτα', '', 'img/sokolata.webp'],
  ['σπίτι', '', 'img/spiti.webp'],
  ['σταφύλι', '', 'img/stafyli.webp'],
  ['στόμα', '', 'img/stoma.webp'],
  ['σύννεφο', '', 'img/synnefo.webp'],
  ['σφουγγάρι', '', 'img/sfouggari.webp'],
  ['σώμα', '', 'img/soma.webp'],
  ['ταξί', '', 'img/taxi.webp'],
  ['τετράδιο', '', 'img/tetradio.webp'],
  ['τηγάνι', '', 'img/tigani.webp'],
  ['τηλεσκόπιο', '', 'img/tileskopio.webp'],
  ['τηλεόραση', '', 'img/tileorasi.webp'],
  ['τίγρης', '', 'img/tigris.webp'],
  ['τιμόνι', '', 'img/timoni.webp'],
  ['τόξο', '', 'img/toxo.webp'],
  ['τόπι', '', 'img/topi.webp'],
  ['τούρτα', '', 'img/tourta.webp'],
  ['τρένο', '', 'img/treno.webp'],
  ['τρακτέρ', '', 'img/trakter.webp'],
  ['τραπέζι', '', 'img/trapezi.webp'],
  ['τρίγωνο', '', 'img/trigono.webp'],
  ['τσάντα', '', 'img/tsada.webp'],
  ['τυρί', '', 'img/tyri.webp'],
  ['τόνος', '', 'img/tonos.webp'],
  ['ρίζα', '', 'img/riza.webp'],
  ['ραδιόφωνο', '', 'img/radiofono.webp'],
  ['ρακέτα', '', 'img/raketa.webp'],
  ['ρινόκερος', '', 'img/rinokeros.webp'],
  ['ρολόι', '', 'img/roloi.webp'],
  ['ρόμπα', '', 'img/roba.webp'],
  ['ρομπότ', '', 'img/robot.webp'],
  ['ρόδα', '', 'img/roda.webp'],
  ['ρύζι', '', 'img/ryzi.webp'],
  ['ήρωας', '', 'img/iroas.webp'],
  ['θεός', '', 'img/theos.webp'],
  ['θρανίο', '', 'img/thranio.webp'],
  ['παππούς', '', 'img/pappous.webp'],
];

// Ομάδες λέξεων με παρόμοιες εικόνες: δεν εμφανίζονται ποτέ μαζί ως «σωστή» και «παγίδα»,
// ώστε να μη μπερδεύεται το παιδί (π.χ. λαγός/κουνέλι, βάρκα/καράβι).
const CONFLICTS = [
  ['βάρκα', 'βαπόρι', 'καράβι', 'πλοίο', 'ιστιοφόρο', 'κανό'],
  ['λαγός', 'κουνέλι'],
  ['ψάρι', 'ψαράς', 'τόνος', 'ξιφίας'],
  ['πουλί', 'καναρίνι', 'γεράκι', 'χήνα', 'παπαγάλος', 'πάπια', 'παπί', 'κότα', 'κόκορας', 'πιγκουίνος'],
  ['αγελάδα', 'βόδι'],
  ['ρολόι', 'ώρα', 'ξυπνητήρι'],
  ['ήλιος', 'μέρα'],
  ['θάλασσα', 'ωκεανός'],
  ['δωμάτιο', 'σαλόνι'],
  ['βέλος', 'τόξο'],
  ['βιβλίο', 'τετράδιο', 'σελίδα'],
  ['δέντρο', 'δάσος'],
  ['βουνό', 'λόφος'],
  ['λουλούδι', 'λουλουδάκι', 'ηλιοτρόπιο'],
  ['παπούτσι', 'σανδάλι'],
  ['χέρι', 'δάχτυλο', 'νύχια'],
  ['ψητό', 'κότα', 'κόκορας'],
  ['σαλάτα', 'λάχανο'],
  ['τυρί', 'φέτα'],
  ['καζάνι', 'τηγάνι'],
  ['ποτήρι', 'γάλα', 'ποτό', 'πορτοκαλάδα'],
  ['χιόνι', 'νιφάδα', 'χαλάζι'],
  ['σύννεφο', 'βροχή', 'θύελλα'],
  ['καρέκλα', 'θέση'],
  ['ραδιόφωνο', 'ηχείο'],
];

// Λέξεις που επιτρέπονται στο στάδιο «Γράφω τις λέξεις» ακόμα κι αν έχουν δίψηφο, διπλό γράμμα ή είναι μεγάλες.
const WRITE_ALLOW = ['ήλιος', 'ηχείο', 'ημερολόγιο', 'ωκεανός', 'θάλασσα', 'θύελλα', 'θυμάρι', 'ιπποπόταμος', 'ιππότης'];
